---
title: "Shot Noise Analysis"
author: "Kantnerova et al. (2023)"
date: "`r format(Sys.Date(), '%d %b %Y')`"
number-sections: false
toc: true
toc-depth: 2
fig-width: 8
fig-height: 6
df-print: tibble
embed-resources: true
format:
  html:
    code-tools: true
    code-fold: false
    code-summary: "Show the code"
    toc-float: true
crossref:
  fig-prefix: Fig.
  tbl-prefix: Table
  ref-hyperlink: true
editor: source
editor_options:
  chunk_output_type: console
---

# Setup

Using `r R.version.string` , @R, tidyverse version `r packageVersion("tidyverse")`, @tidyverse, and isoorbi version `r packageVersion("isoorbi")`.

```{r}
#| label: setup
#| message: false

# load packages
library(isoorbi) # for orbitrap function
library(dplyr) # for mutating data frames
library(forcats) # for recoding factors
library(ggplot2) # for data visualization
library(cowplot) # arrange multipanel plots
```

```{r, include=FALSE}
#| label: global knitting options for code rendering
knitr::opts_chunk$set(
  collapse = TRUE, comment = "#>",
  dev = c("png", "pdf"), fig.keep = "all",
  dev.args = list(pdf = list(encoding = "WinAnsi", useDingbats = FALSE)),
  fig.path = sprintf("plots/%s_", gsub("\\.rmarkdown", "", knitr::current_input()))
)
```

# Model Peptide (MRFA)

## Data

```{r}
#| label: calculate shot noise
shot_noise_aas <-
  "data" |>
  orbi_find_isox() |> # finds all .isox files in a folder
  orbi_read_isox() |> # reads the .isox files into a tibble data frame
  orbi_simplify_isox() |> # keeps only columns that are directly relevant for isotopocule ratio analysis
  orbi_flag_satellite_peaks() |> # flags minor signals (e.g., satellite peaks) that were reported by IsoX
  orbi_flag_weak_isotopocules(min_percent = 10) |> # flags isotopocules that are not consistently detected in most scans
  orbi_flag_outliers(agc_window = c(2, 98)) |> # flags outliers based on a TIC x IT criteria
  orbi_define_basepeak("M0") |> # sets one isotopocule in the data frame as the base peak (ratio denominator)
  orbi_filter_flagged_data() |> # filters out data that have been flagged using the previous functions
  orbi_analyze_shot_noise() |> # does the shot noise calculation
  orbi_export_data_to_excel("shot_noise_MRFA.xlsx") # exports the final dataset into an Excel file
```

## Table

```{r}
#| label: example of first few rows
shot_noise_aas |>
  orbi_filter_isox(filename = levels(shot_noise_aas$filename)[1]) |>
  arrange(compound, isotopocule, scan.no) |>
  head(10) |>
  select(compound, scan.no, time.min, isotopocule,
         ratio, ratio_rel_se.permil, shot_noise.permil) |>
  knitr::kable()
```

## Figure: Amino Acids - Shot Noise

```{r}
#| label: fig-shotnoise-mrfa
#| fig-cap: amino acids shotnoise
#| warning: false
#| fig-width: 8
#| fig-height: 8
shot_noise_aas |>
  filter(compound == "Met_imm" | isotopocule != "2H") |>
  # change panel titles
  mutate(
    compound = compound |>
      fct_recode(
        "Alanine" = "Ala_imm",
        "Arginine" = "Arg_imm",
        "Methionine" = "Met_imm",
        "Phenylalanine" = "Phe_imm"
      )
  ) |>
  orbi_plot_shot_noise()
```
