---
title: "Replicates"
author: "Kantnerova et al. (2023)"
date: "`r format(Sys.Date(), '%d %b %Y')`"
number-sections: false
toc: true
toc-depth: 2
fig-width: 8
fig-height: 6
df-print: tibble
embed-resources: true
format: 
  html: 
    code-tools: true
    code-fold: false
    code-summary: "Show the code"
    toc-float: true
crossref:
  fig-prefix: Fig.
  tbl-prefix: Table
  ref-hyperlink: true
editor: source
editor_options: 
  chunk_output_type: console
---

# Setup

Using `r R.version.string` , @R, tidyverse version `r packageVersion("tidyverse")`, @tidyverse, and isoorbi version `r packageVersion("isoorbi")`.

```{r}
#| label: setup
#| message: false

# load packages
library(isoorbi) # for orbitrap function
library(dplyr) # for mutating data frames
library(stringr) # for extarcting text information
library(forcats) # for recoding factors
library(ggplot2) # for data visualization
library(cowplot) # arrange multipanel plots
```

```{r, include=FALSE}
#| label: global knitting options for code rendering
knitr::opts_chunk$set(
  collapse = TRUE, comment = "#>",
  dev = c("png", "pdf"), fig.keep = "all",
  dev.args = list(pdf = list(encoding = "WinAnsi", useDingbats = FALSE)),
  fig.path = sprintf("plots/%s_", gsub("\\.rmarkdown", "", knitr::current_input()))
)
```

# Data

```{r}
#| label: isotopocule data
data <- 
  "data" |>
  orbi_find_isox() |> # finds all .isox files in a folder
  orbi_read_isox() |> # reads the .isox files into a tibble data frame
  orbi_flag_satellite_peaks() |> # flags minor signals (e.g., satellite peaks) that were reported by IsoX
  orbi_flag_weak_isotopocules(min_percent = 30) |> # flags isotopocules that are not consistently detected in most scans
  orbi_flag_outliers(agc_window = c(2, 98)) |> # flags outliers based on a TIC x IT criteria
  orbi_filter_flagged_data() |> # filters out data that have been flagged using the previous functions
  # pull out replicate from filename
  mutate(
    replicate = str_extract(filename, "Replicate_\\d") |> str_replace("_", " ")
  ) |>
  # expand amino acid names
  mutate(
    compound = compound |>
      fct_recode(
        "Alanine" = "Ala_imm",
        "Arginine" = "Arg_imm",
        "Methionine" = "Met_imm",
        "Phenylalanine" = "Phe_imm"
      )
  )

# calculate ratios for 13C/M0
ratios <- data |>
  orbi_define_basepeak("M0") |> # sets one isotopocule in the data frame as the base peak (ratio denominator)
  orbi_filter_isox(isotopocules = "13C") |> # selects only a particular isotopocule, can be also used for compound or time range
  group_by(replicate) |>
  orbi_summarize_results(ratio_method = "sum") # generates the results table

ratios  |> orbi_export_data_to_excel("MRFA_data_replicates.xlsx") # exports the final dataset into an Excel file
```

# Figure - top panel

```{r}
#| label: fig-replicates-top

p_top <- 
  data |>
  filter(isotopocule == "M0") |>
  # plot setup
  ggplot() +
  aes(time.min, intensity, color = compound) + 
  geom_line() +
  facet_grid(. ~ replicate) +
  # scales
  scale_y_log10(
    breaks = c(5e6, 1e7, 2e7), 
    labels = expression(5 %*% 10^6, 1%*%10^7, 2%*%10^7)) +
  scale_color_brewer(palette = "Dark2") +
  scale_x_continuous(breaks = c(5, 10), expand = c(0, 0)) +
  expand_limits(x = 0) + 
  # labels 
  labs(x = "time / min", y = "EIC / arb. unit") +
  # theme
  theme_bw() +
  theme(
    text = element_text(size = 16),
    panel.grid = element_blank(),
    strip.background = element_blank()
  )
p_top
```

# Figure - bottom panel

```{r}
#| label: fig-replicates-bottom

p_bottom <- 
  ratios |>
  ggplot() +
  aes(
    replicate, ratio, color = compound, shape = compound,
    ymin = ratio - ratio_sem, ymax = ratio + ratio_sem
  ) +
  # standard deviations
  geom_rect(
    data = function(df) 
      df |> group_by(compound) |>
      summarize(ratio_mean = mean(ratio), ratio_sd = sd(ratio)),
    map = aes(
      ymin = ratio_mean - ratio_sd, ymax = ratio_mean + ratio_sd,
      x = NULL, y = NULL, xmin = -Inf, xmax = +Inf, color = NULL),
    fill = "gray90", show.legend = FALSE
  ) +
  # averages
  geom_hline(
    data = function(df) 
      df |> group_by(compound) |>
      summarize(ratio_mean = mean(ratio)),
    map = aes(yintercept = ratio_mean, color = compound),
    show.legend = FALSE
  ) +
  # data points
  geom_errorbar(width = 0.1, show.legend = FALSE) + 
  geom_point(fill = "white", size = 3) +
  facet_grid(compound ~ ., scales = "free_y") +
  # scales
  scale_color_brewer(palette = "Dark2") +
  scale_shape_manual(values = c(21:25)) +
  scale_y_continuous(breaks = scales::pretty_breaks(3)) +
  # labels
  labs(x = NULL, color = NULL, shape = NULL,
       y = expression("ratio ("^13*C/M0*")")) +
  # theme
  theme_bw() +
  theme(
    text = element_text(size = 16),
    panel.grid = element_blank(),
    strip.background = element_blank(),
    strip.text = element_blank(),
    axis.ticks.x = element_blank(),
    legend.position = "top"
  )
p_bottom
```

# Figure - combined

```{r}
#| label: fig-replicates
#| fig-cap: amino acids replicates
#| warning: false
#| fig-width: 8
#| fig-height: 8
plot_grid(
  p_top + theme(legend.position = "none"), p_bottom,
  ncol = 1, rel_heights = c(1, 2), align = "v", axis = "lr"
)
```
